name: Docker Image CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.IMAGE_NAME }}:latest

    - name: Download Wiz-cli
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: sudo ./wizcli auth --id ${{ secrets.WIZ_CLIENT_ID }} --secret ${{ secrets.WIZ_CLIENT_SECRET }}
      # env:
      #   WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      #   WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    - name: Run wiz-cli docker image scan
      run: sudo ./wizcli docker scan --image ${{ vars.IMAGE_NAME }}:latest --policy ${{ vars.WIZCLI_POLICY_VULNS }} --policy-hits-only --show-vulnerability-details --tag image-name=${{ vars.IMAGE_NAME }} --tag repo=$GITHUB_REPOSITORY --tag repo-owner=$GITHUB_REPOSITORY_OWNER --driver mountWithLayers --group-by layer
